version: "3"

services:
  customer-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      - nats

  nats:
    image: nats:2.10
    ports:
      - "4222:4222"
